### ISSUE TITLE
Page scrolling stops before actual page end

### ISSUE THREAD

**Issue by joelalejandro** [SomosCodear/codear-site#1]
Social media icons aren't fully visible due to a hard stop of the viewport scroll. Apparently is related to how the sticky header works. If I make an additional swipe, the scroll works as expected.

![image](https://user-images.githubusercontent.com/118913/68695938-b9c34880-055a-11ea-8372-5dc8203409f6.png)

**Comment by asermax** [comment]
@joelalejandro is this chrome for android? This looks fine for me on firefox for android.

**Comment by joelalejandro** [comment]
Yeap, it's on Chrome.

**Comment by joelalejandro** [comment]
I think the easiest fix would be to provide some extra padding to the footer.
