### ISSUE TITLE
Redirección a proyecto accedes

### ISSUE THREAD

**Issue by MarianaParedes** [SomosCodear/codear-site#135]
Hola! cómo están, estaba viendo que las urls al proyecto accedes dan not found, no se bien si es momentaneo porque se estan haciendo cambios o es otro tema.

Les dejo el detalle:
- Haciendo clic en el proyecto Accedes del listado de https://linktr.ee/codear, nos dirige a > https://codear.org/acceder Not Found
- Haciendo clic en la url que esta en el canal de youtube ¡Te invitamos a sumarte en https://codear.org/accedes!, nos dirige a >  https://codear.org/accedes! Not Found

Saque el ! y me redirigió al repo que creo que es lo que tiene que estar.

Saludos!

**Comment by joelalejandro** [comment]
¡Gracias @MarianaParedes por avisarnos! Ya corregimos ambos links.
