### ISSUE TITLE
Mejoras en la primera sección de la pagina.

### ISSUE THREAD

**Issue by alexrobaina** [SomosCodear/codear-site#148]
Hola, creé esta issue para sugerir algunos cambios que pienso que sumarian en la web. (obviamente es una sugerencia)
 
Las mejoras que veo serían carousel de los proyectos y el calendario de eventos.

El carousel en la versión mobile se rompe:
<img width="381" alt="Screen Shot 2020-08-05 at 12 06 01" src="https://user-images.githubusercontent.com/30770802/89539928-c071aa00-d7d2-11ea-9c5b-303f19a8cfda.png">

Otro detalle que vi y creo que no es muy complejo de resolver son las proporciones de las imagenes, los botones y los textos de cada proyecto. Pienso que se podrían igualar y mantener las mismas proporciones entre ellos.

Para resolver esto sería ideal resumir los textos y hacer que todos tengan la misma cantidad de caracteres.

<img width="1185" alt="Screen Shot 2020-08-05 at 12 09 05" src="https://user-images.githubusercontent.com/30770802/89540369-4ee62b80-d7d3-11ea-8f54-f21b7381dfb4.png">

Adjunto dos bocetos de lo que me imagino

![Codear 2](https://user-images.githubusercontent.com/30770802/89543508-69220880-d7d7-11ea-8e09-c0898203ce98.png)
![Codear 1](https://user-images.githubusercontent.com/30770802/89543563-7939e800-d7d7-11ea-92b1-67ef2c3b10e9.png)

Si les parece bien y les gusta la idea puedo hacer un branch y cuando lo tenga listo hago el PR :)
Gracias!

**Comment by joelalejandro** [comment]
¡Hola @alexrobaina! Gracias por querer darnos una mano con este tema. Estábamos pensando con el equipo en explorar una versión más ancha del calendario para que los nombres de los eventos se vean mejor y tener una fila dedicada a los proyectos. ¿Qué te parece?

**Comment by alexrobaina** [comment]
Hola @joelalejandro Gracias a ustedes, es un gusto colaborar! 
Respecto a lo que comentas del calendario y los proyectos me parece buena idea.

Si quieres vemos primero lo del calendario, ¿te parece bien?
Hice un boceto con cajitas más alargadas y creo que el problema el nombre va seguir estando, sobretodo en patanllas de 13 pulgadas. 
Adjunto boceto de W: 1360px - H: 768px
![Web 1366 – 2](https://user-images.githubusercontent.com/30770802/89845558-38363080-db55-11ea-8e6c-1a92b7c6ec17.png)

Por otro lado viendo lo que ya esta hecho en la versión mobile hice este boceto que creo que también puede andar: 
![Web 1366 – 1](https://user-images.githubusercontent.com/30770802/89845731-ab3fa700-db55-11ea-8afc-c8a16f13b792.png)

En este caso el problema que veo es cuando solo hay un evento en el mes? Mm... Quizas se pueden hacer cajitas similares pero con los eventos viejos que te lleven al video en youtube (?)

Que opinas?

**Comment by joelalejandro** [comment]
¡Geniales ideas @alexrobaina! Creo que podemos hacer una combinación de lo mejor de ambos mundos.

Podemos habilitar como vista predeterminada la opción de los eventos en formato mobile como se ve en tu segundo boceto, pero sólamente mostraríamos los eventos futuros. La mayoría de los links que cargamos en el JSON de eventos apunta a Meetup, Eventbrite o sitios que al finalizar el evento no aportan mucha información útil, y no de todos quedan grabaciones. (De todos modos, es algo que podemos revisar por otro lado).

Me imagino que podríamos agregar una opción "Ver como calendario" que muestre la vista de tu primer boceto, pero en pantalla completa. Ahí podemos aprovechar todo el espacio disponible. 

¿Qué te parece?

**Comment by alexrobaina** [comment]
Genial @joelalejandro me copa la combinación de los mundos 👍 
Vale, Ahi respondí la #151 @asermax tiene razon con lo que dice y no se rompe.

Ok, entiendo lo que dices respecto a los links, tiene sentido lo que planteas :).
Ma parece super lo del boton "ver como calendario" y poder cambiar de mundo y bueno en mobile no existiría ese boton (?), si quieres mañana armo un bocetito con el boton y las dos vistas a ver que te parece. 

Te parece bien?

**Comment by joelalejandro** [comment]
¡Vamos para adelante!

**Comment by alexrobaina** [comment]
Hola @joelalejandro como va? 
Adjunto capturas de lo que estuve armando, creo que puede ir bien. 
Avisame si te parece bien o si te surge alguna duda o sugerencia y si esta todo bien comienzo.

![Web 1366 – 1](https://user-images.githubusercontent.com/30770802/90202478-374f0a00-ddb4-11ea-9466-f4727978774e.png)
![Web 1366 – 2](https://user-images.githubusercontent.com/30770802/90202483-3a49fa80-ddb4-11ea-9f01-b94db351e6eb.png)

**Comment by alexrobaina** [comment]
Adjunto nuevos bocetos, me parece que asi van mejor.
¿Que te parece? 

![Web 1366 – 1](https://user-images.githubusercontent.com/30770802/90305240-df3d0400-de96-11ea-8ea6-faca1519a9b9.png)
![Web 1366 – 2](https://user-images.githubusercontent.com/30770802/90305243-e237f480-de96-11ea-9523-641eb2a1e02f.png)

**Comment by joelalejandro** [comment]
@alexrobaina ¡Disculpa la demora! Vamos por los botones separados Ver como calendario/Ver como grilla, y alinéandolos a la derecha y antes del contenido:

![image](https://user-images.githubusercontent.com/118913/90313686-c6f3d600-dee4-11ea-87a6-f6d729722d8e.png)

**Comment by alexrobaina** [comment]
Hola @joelalejandro no te preocupes, yo estuve con mucho laburo y también me demoré.
Vale genial, voy por ese camino.

Muchas gracias 👍

**Comment by alexrobaina** [comment]
Hola @joelalejandro Como andas?
Escribo para avisar que avanzé bastante con la issue sin mayores problemas. Calculo que para la semana que 
viene (Lunes, martes) hago el PR.

Saludos.

**Comment by joelalejandro** [comment]
Resuelto vía #161.

**Comment by joelalejandro** [comment]
Cierro este issue, creé #169 para llevar adelante los cambios para Proyectos.
