### ISSUE TITLE
Corregir imagen de sugerencia al compartir link de CoDeAr (Open Graph)

### ISSUE THREAD

**Issue by mmoyano16** [SomosCodear/codear-site#187]
Cuando se quiere compartir el link del sitio oficial de CoDeAR (https://codear.org), al mostrar la info sugerida del link, la imagen sale asociada a RefactorDevs (anteriormente el logo de ReactCba)

![image](https://user-images.githubusercontent.com/5847516/96160693-aea43580-0eec-11eb-9bf6-c121d2bcd165.png)

Está sucediendo por lo pronto tanto en Facebook como en Instagram cuando mandas PMs

**Comment by joelalejandro** [comment]
El misterio que tiene este issue es _increíble_. Me puse a hurgar qué hace Instagram por ejemplo para determinar qué hace con el link, y encontré este payload:

```json
[
  {
    "event":"patch",
    "data":[
      {
        "op":"add",
        "path":"/direct_v2/threads/340282366841710300949128122982381347573/items/29566699765468479586202063380414464",
        "value":"{\"item_id\": \"29566699765468479586202063380414464\", \"user_id\": 31793544, \"timestamp\": 1602814005947379, \"item_type\": \"link\", \"link\": {\"text\": \"https://codear.org\", \"link_context\": {\"link_url\": \"https://codear.org\", \"link_title\": \"CoDeAr | Comunidad de Desarrolladores de Argentina\", \"link_summary\": \"Somos una asociaci\\u00f3n civil dedicada a la formaci\\u00f3n y difusi\\u00f3n de conocimientos de tecnolog\\u00eda, aplic\\u00e1ndola como un instrumento transformador y potenciador para la sociedad.\", \"link_image_url\": \"https://external.xx.fbcdn.net/safe_image.php?d=AQBydKkqBA_t2wd0\\u0026w=1080\\u0026h=600\\u0026url=https%3A%2F%2Fcodear.org%2Fimages%2Fcommunity-logos%2Frefactor-devs.jpg\\u0026upscale=1\\u0026_nc_cb=1\\u0026_nc_hash=AQDrTB0hc-YUH02Z\"}, \"client_context\": \"6722689195618346083\", \"mutation_token\": \"6722689195523320945\"}, \"client_context\": \"6722689195618346083\", \"show_forward_attribution\": false, \"is_shh_mode\": false}"
      }
    ],
    "message_type":1,
    "seq_id":47014,
    "mutation_token":"6722689195523320945",
    "realtime":true
  }
]
```

Hurgando más en profundidad en ese mismo payload, encontré esto:

```json
{
  "item_id":"29566699765468479586202063380414464",
  "user_id":31793544,
  "timestamp":1602814005947379,
  "item_type":"link",
  "link":{
    "text":"https://codear.org",
    "link_context":{
      "link_url":"https://codear.org",
      "link_title":"CoDeAr | Comunidad de Desarrolladores de Argentina",
      "link_summary":"Somos una asociaci\\u00f3n civil dedicada a la formaci\\u00f3n y difusi\\u00f3n de conocimientos de tecnolog\\u00eda, aplic\\u00e1ndola como un instrumento transformador y potenciador para la sociedad.",
      "link_image_url":"https://external.xx.fbcdn.net/safe_image.php?d=AQBydKkqBA_t2wd0\\u0026w=1080\\u0026h=600\\u0026url=https%3A%2F%2Fcodear.org%2Fimages%2Fcommunity-logos%2Frefactor-devs.jpg\\u0026upscale=1\\u0026_nc_cb=1\\u0026_nc_hash=AQDrTB0hc-YUH02Z"
    },
    "client_context":"6722689195618346083",
    "mutation_token":"6722689195523320945"
  },
  "client_context":"6722689195618346083",
  "show_forward_attribution":false,
  "is_shh_mode":false
}
```

Y si limpiamos un poco la URL:

https://external.xx.fbcdn.net/safe_image.php?d=AQBydKkqBA_t2wd0&w=1080&h=600&url=https%3A%2F%2Fcodear.org%2Fimages%2Fcommunity-logos%2Frefactor-devs.jpg&upscale=1&_nc_cb=1&_nc_hash=AQDrTB0hc-YUH02Z

Encontramos que ese es el link a la imagen que se ve en el screenshot.

Ahora, hay que ver por qué Facebook decide mostrar esa imagen.

**Comment by joelalejandro** [comment]
Bueno, nada, tanto misterio se reduce a lo que dice clarito el depurador de Open Graph:

https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fcodear.org

Básicamente, la imagen que usamos mide menos de 200 píxeles, entonces Facebook busca la siguiente que cumpla ese requerimiento.

**Comment by joelalejandro** [comment]
![image](https://user-images.githubusercontent.com/118913/96209283-99a7c080-0f45-11eb-981e-5f1e7edb4280.png)

Quedó corregido @mmoyano16 🚀
