### ISSUE TITLE
Fix typos in team member names

### ISSUE THREAD

**Issue by joelalejandro** [SomosCodear/codear-site#4]
Agustin => Agust<b>í</b>n
Carillo => Car<b>r</b>illo

![image](https://user-images.githubusercontent.com/118913/68696488-d90ea580-055b-11ea-8008-ed304d85a4ee.png)

**Comment by asermax** [comment]
I've been always told I can write my name however I want, so I never use a tilde :stuck_out_tongue_closed_eyes:
